### ISSUE TITLE
Shinken 2.2 Roadmap

### ISSUE THREAD

**Issue by Seb-Solon** [naparuba/shinken#1175]
Let's define the 2.2 Roadmap!

==================================

- [x] Add snapshots commands launch and backup @naparuba

- [x] Cherry-pick commit from @htgoebel PR regarding Code Quality : #608 (@Seb-Solon)
- [x] Merge (or not) all other PR open since a long time : #1091 #1076 #1069 #1017 #792 #608 #567 #566  (@Seb-Solon)
- [x] Enhance documentation :   (@Seb-Solon)
- [x] Enhance test : Add short/long test in modules also (new_runtest.sh) (@Seb-Solon)

- [x] Fix **reproductible** bugs (@shinken-monitoring)

================================

Feel free to edit this message and start a real roadmap :)
