### ISSUE TITLE
2.2 Checklist

### ISSUE THREAD

**Issue by Seb-Solon** [naparuba/shinken#1419]
Here we go for a checklist to release (taken from https://gist.github.com/Frescha/8398527): 

- [x] Unlabel  "CURRENT ROADMAP" on the related issue on Github
- [x] Update Changelog
- [x] Update version number in `shinken/bin.py`
- [x] Update version number in `setup.py`
- [x] Run the tests:
```
cd test && ./quick_tests.sh
```

- [x] Commit the changes: 
```
git add -u
git commit -m "Release 2.2-RCX"
```

- [x] Release on PyPI:
```
python setup.py shinken upload
```

- [ ] Test that it pip installs (on several distro) :
```
mktmpenv
pip install shinken
deactivate
```

- [x] Tag the last git commit with the version number:
```
git tag -a 2.2-RCX
```

- [x] Push: `git push`
- [x] Push tags: `git push --tags`
- [ ] Edit the release on GitHub. Paste the release notes into the release's release page, and come up with a title for the release.
- [ ] Send a mail to the devel-list
