### ISSUE TITLE
 Shinken 2.4 Roadmap

### ISSUE THREAD

**Issue by Seb-Solon** [naparuba/shinken#1451]
Let's define the 2.4 Roadmap!

==================================

- [x]  Pep8 Shinken Code : #1393  (@Seb-Solon, @titilambert, @gst)
- [x] Feature : include_service keyword for packs: https://github.com/naparuba/shinken/issues/1477 (@gst)
- [x] Rework setup.py : #1467 (@Seb-Solon, @titilambert, @gst, @ddurieux )

- [x] "Native" plugin (plugin imported as python module once and "directly" executed in python) (@gst)       (Maybe outside shinken core, in a new poller module)

Release will be on 31/03/2015. See #1394

================================

Feel free to edit this message :)

**Comment by naparuba** [comment]
We will start with addings hosts, not service or others object. hosts are what is important,the other can wait. Will be still a nightmare to manage in a clean way hosts :)

**Comment by naparuba** [comment]
and i remove bug fix. It's a "of course" entry :)

**Comment by gst** [comment]
Le 2015-01-13 03:45, Gabès Jean a écrit :
> We will start with addings hosts, not service or others object. hosts are what is important,the other can wait. Will be still a nightmare to manage in a clean way hosts :)

Alright.

But first we should define/talk about - unless I missed it (I hope not) 
- a proof of concept / a way of how this would be achieved.. shouldn't we ?

What I merely see as first possibility (throw at me stones if you see I 
say (I may) idiots things regarding the current possibilities / way of 
doing) ;) :

add to the Arbiter Interface (IForArbiter) a new method :

defadd_config_block(self,config_block):
     ''' Dynamically parse and load a config block (unicode) to the current config.

     :param  config_block: The string(unicode) representing a new block of config to be added.
         ex:
         config_block = """define host {
             use generic-host
             host_name localhost
         }"""
     :return: Nothing(None) if succeeded. The corresponding block of config will then be dynamically loaded (before the return occurs).
     :raise: `Some´ exception (TBD) in case the parsing or the config_block would fail for any reason (unknown template, etc..)
     '''
     config_block = config_block.strip()
     if notconfig_block:# trivial case
         return

That's it ! :o  wdyt ?

With such an interface/API, we are already future-ready for any kind of 
config item.. and it's also possible to add many hosts (or in the future 
any kind of config part finally, as far as it's valid) at once.

But that's only for the interface/api and that's only one possibility ; 
now at the implementation level I would personally need to re-study how 
the config is managed & dispatched by the arbiter more precisely .. 
that's the hard thing of course and we shouldn't rush too fast into it 
before understanding the ins & the outs, at least most of them  ;)


-- 
Grégory Starck

Ingénieur logiciel
Savoir-faire Linux
Email: gregory.starck@savoirfairelinux.com
Tél: +1 514 276 5468 Poste #176

**Comment by naparuba** [comment]
The real problem is not the api, really. this wil be managed in few minutes
(even if I prefer to have a json entry, will be quit easier to manage and
grok but it's more a detail than something else).


The realm challenge is what object.property can be add/change without
global impact (if you add a template this can have a huge impact for nearly
all obejcts, so you have to do the whole configuration load even for one
small object).

That's why I limit this first version to host (not template, real hosts
that are using real objects and service definition that are already
exists). Even with this, there are still some tricky part (depdency that
force a 2 configuration pack merge? not managed currentl for example).

If all ofthis is simpler than expected, we can still add things. But I
really think this won't be so simple, we are modifying the core concept,
and such thing always got huge impacts to several levels (we talk about
arbiter, but scheduler and brokers are also impacted in fact in the way
they are getting the hosts for example).

One step after the other so ^^

**Comment by andyxning** [comment]
Can we just think about External Commands. I have also thought about this sometimes. I think External Commands may give us a another road to achieve this.

* before, we do any run-time update about the configurations in Shinken, we should run shinken-arbiter to check if the update is correct. However, the existing  External Commands is not enough to accomplish this job. If available, we think that  we should add some more Commands.
* If, the check is passed without error or conflict. Then, we can invoke External Commands to do this update.

**Comment by gst** [comment]
FYI:
- [ ] "Native" plugin (plugin imported as python module once and "directly" executed in python) (@gst) (Maybe outside shinken core, in a new poller module)

=> https://github.com/shinken-monitoring/mod-native-plugins (WIP)
