### ISSUE TITLE
Shinken 2.6 Roadmap

### ISSUE THREAD

**Issue by titilambert** [naparuba/shinken#1530]
Let's define the 2.6 Roadmap!

==================================

- [ ] Pylint Shinken Code : #1393  (@Seb-Solon, @titilambert, @gst)
- [ ] Improve tests to detect regressions : #TDB (@Seb-Solon, @titilambert, @gst)
- [ ] Refactoring: Refactor list parsing in configuration (empty string should be casted "[]" or "None") (ie: contactgroups parameter)
- [ ] Feature : Add/[remove] host without arbiter restart #1454 (@naparuba)
- [ ] Doc cleaning #TBD (@shinken-monitoring)

Release will be on 23/06/2015. See #1394

================================

Feel free to edit this message :)

**Comment by GrdNico** [comment]
Hi, Release Date is incorrect... I think :)

Regards,

**Comment by naparuba** [comment]
yep, I'll update it so we did prefer to focus on a hard rock solid 2.4
instead ^^
